spring:
  application:
    name: pd-mews
server:
  port: 8081
  datasource:
    # url: jdbc:postgresql://localhost:5432/pdmews_db
    # username: pdmews_user
    # password: secure_password
    # driver-class-name: org.postgresql.Driver
    url: jdbc:h2:mem:pdmews_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.pdmews: DEBUG
    org.springframework.web: INFO

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day
